spring.application.name=campusequipmentloan

#Default Login
spring.security.user.name=admin
spring.security.user.password=admin123

# Database config
spring.datasource.url=jdbc:h2:mem:campusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
